date.timezone = Asia/Tokyo

; 開発時はエラーを表示（本番では off を推奨）
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; 文字コード
default_charset = "UTF-8"

; アップロード/POSTサイズ
upload_max_filesize = 16M
post_max_size = 16M
